using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SoundRentalApp.Models;

namespace SoundRentalApp.Services.Pdf;

public class RentalInvoiceDocument : IDocument
{
    private readonly RentalHeader _rental;

    public RentalInvoiceDocument(RentalHeader rental)
    {
        _rental = rental;
    }

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Margin(30);

            page.Header()
                .Text("Rental Invoice")
                .FontSize(20)
                .Bold();

            page.Content().Column(col =>
            {
                col.Item().Text($"Rental Number : {_rental.RentalNumber}");
                col.Item().Text($"Customer : {_rental.Customer?.CustomerName}");
                col.Item().Text($"Rental Date : {_rental.RentalDate:dd/MM/yyyy}");
                col.Item().Text($"Return Date : {_rental.ReturnDate:dd/MM/yyyy}");
                col.Item().Text($"Grand Total : Rp {_rental.GrandTotal:N0}");
                col.Item().Text($"Down Payment : Rp {_rental.DownPayment:N0}");
                col.Item().Text($"Remaining : Rp {_rental.RemainingPayment:N0}");
            });

            page.Footer()
                .AlignCenter()
                .Text(x =>
                {
                    x.Span("Generated by SoundRentalApp");
                });
        });
    }
}